# Generated by Django 5.2.12 on 2026-04-10 09:24

import django.db.models.deletion
import provider_settings.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('groq', 'Groq'), ('ollama', 'Ollama'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic')], max_length=32)),
                ('api_key', provider_settings.fields.EncryptedTextField(blank=True, default='')),
                ('model_name', models.CharField(max_length=128)),
                ('base_url', models.CharField(blank=True, default='', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('fallback_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fallback_order'],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider')],
            },
        ),
    ]
