# Generated by Django 5.2.12 on 2026-04-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('research', 'research'), ('pm', 'pm'), ('system_designer', 'system_designer'), ('db_schema', 'db_schema'), ('api_designer', 'api_designer'), ('code_review', 'code_review'), ('bug_fixer', 'bug_fixer'), ('testing', 'testing'), ('documentation', 'documentation')], max_length=32)),
                ('target_artifact', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_slice', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('provider_used', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.pipeline')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['pipeline', 'agent_type'], name='agents_agen_pipelin_b47ea1_idx'), models.Index(fields=['status'], name='agents_agen_status_9136dc_idx')],
            },
        ),
    ]
